#!/usr/bin/env python3
"""Drive relay: how scheduled Claude sessions get their work into the repository.

Scheduled sessions can clone this public repository but cannot push to it. So a
session works on its local clone as usual and, after every step, packs the text
files it changed into one plain-text *change bundle*, which it uploads to the
Google Drive production folder. A GitHub Action (.github/workflows/relay.yml)
downloads new bundles every 10 minutes, checks them, applies them in order,
regenerates everything derived (maps from their generators, episodes from their
fixtures: the engine is deterministic), runs the tests, commits and pushes.

Session side
    python3 scripts/relay.py begin SESSION            # once, right after cloning
    python3 scripts/relay.py pack "message" [--episode-commit N]
        -> writes .relay/out/<name>.txt and prints the Drive upload to make
    python3 scripts/relay.py pending NAMES.txt        # which uploaded bundles the repo hasn't applied yet

Action side
    DRIVE_API_KEY=... python3 scripts/relay.py check-drive   # prints new=<n>
    DRIVE_API_KEY=... python3 scripts/relay.py apply-drive
    python3 scripts/relay.py apply-dir DIR            # same, from local files (tests)

Bundle format (text/plain, so it can be uploaded verbatim with no escaping):

    PQC-CHANGE 1
    name: change-20261005T221500Z-overnight-20261005-2207-001
    session: overnight-20261005-2207
    base: <commit the session started from>
    message: Episode 2: plan
    run: episode_commit 2                (optional, repeatable)
    === FILE fixtures/C01-E002/plan.json sha256=<hex> lines=<n>
    <the file, verbatim>
    === B64 assets/sprites/pell.png sha256=<hex>
    <base64 lines>
    === DELETE some/old/file
    === END
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "production" / "relay.json"
APPLIED = ROOT / "production" / "applied.json"
STATE = ROOT / ".relay" / "state.json"
OUT = ROOT / ".relay" / "out"
MARKER = "refs/relay/last"
API = "https://www.googleapis.com/drive/v3/files"
NAME_RE = re.compile(r"^change-\d{8}T\d{6}Z-[A-Za-z0-9_.-]+-\d{3}(\.txt)?$")
MAX_BUNDLE = 60_000          # characters per upload; bigger changes are split into parts
MAX_BINARY = 24_000          # bytes; sprites and small images only

# What a session may change. Everything else is regenerated by the Action.
ALLOWED = (re.compile(r"^(fixtures|scripts|pqc|prompts|schemas|tests|campaign|wiki/data)/"),
           re.compile(r"^assets/(manifest\.json|maps/[^/]+\.json|sprites/.+)$"),
           re.compile(r"^production/(queue\.json|LOG\.md)$"),
           re.compile(r"^bible/RETCONS\.md$"), re.compile(r"^README\.md$"))
DERIVED = re.compile(r"^(episodes/|state/|wiki/docs/|production/previews/|production/applied\.json|out/|render_out/)")


def git(*args, check=True) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, check=check).stdout


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def allowed(path: str) -> bool:
    return any(r.match(path) for r in ALLOWED) and not DERIVED.match(path)


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


# ------------------------------------------------------------------ session side
def begin(session: str) -> int:
    STATE.parent.mkdir(exist_ok=True)
    (ROOT / ".relay" / ".gitignore").write_text("*\n")
    head = git("rev-parse", "HEAD").strip()
    git("update-ref", MARKER, head)
    STATE.write_text(json.dumps({"session": session, "base": head, "seq": 0}))
    print(f"relay ready: session {session}, base {head[:7]}")
    return 0


def _encode(paths_status: list[tuple[str, str]]) -> tuple[list[str], list[str]]:
    """Body blocks for each changed path, plus paths that can't be relayed."""
    blocks, refused = [], []
    for status, path in paths_status:
        if not allowed(path):
            if not DERIVED.match(path):
                refused.append(path)
            continue
        if status == "D":
            blocks.append(f"=== DELETE {path}\n")
            continue
        data = (ROOT / path).read_bytes()
        try:
            text = data.decode("utf-8")
            if "\n=== " in "\n" + text or "\r" in text:
                raise UnicodeDecodeError("utf-8", data, 0, 1, "delimiter or CR in text")
            body = text if text.endswith("\n") else text + "\n"   # a final newline is added if missing
            blocks.append(f"=== FILE {path} sha256={sha(body.encode())} lines={body.count(chr(10))}\n{body}")
        except UnicodeDecodeError:
            if len(data) > MAX_BINARY:
                refused.append(f"{path} (binary, {len(data)} bytes > {MAX_BINARY})")
                continue
            b64 = base64.encodebytes(data).decode()
            blocks.append(f"=== B64 {path} sha256={sha(data)}\n{b64}")
    return blocks, refused


def pack(message: str, episode_commit: list[int]) -> int:
    st = json.loads(STATE.read_text())
    git("add", "-A")
    diff = git("diff", "--cached", "--no-renames", "--name-status", MARKER)
    changed = [tuple(line.split("\t", 1)) for line in diff.splitlines() if line.strip()]
    blocks, refused = _encode(changed)
    if refused:
        print("These changes can't be relayed (outside the allowed paths, or binary too big):")
        for r in refused:
            print(f"  {r}")
        print("Undo them or move them; nothing was packed.")
        return 1
    if not blocks and not episode_commit:
        print("Nothing to pack.")
        return 0
    parts, cur = [], []
    for b in blocks:
        if cur and sum(map(len, cur)) + len(b) > MAX_BUNDLE:
            parts.append(cur)
            cur = []
        cur.append(b)
    parts.append(cur)
    OUT.mkdir(parents=True, exist_ok=True)
    names = []
    for i, part in enumerate(parts):
        st["seq"] += 1
        name = f"change-{now()}-{st['session']}-{st['seq']:03d}"
        head = [f"PQC-CHANGE 1", f"name: {name}", f"session: {st['session']}", f"base: {st['base']}",
                f"message: {message}" + (f" (part {i + 1}/{len(parts)})" if len(parts) > 1 else "")]
        if i == len(parts) - 1:
            head += [f"run: episode_commit {n}" for n in episode_commit]
        text = "\n".join(head) + "\n" + "".join(part) + "=== END\n"
        (OUT / f"{name}.txt").write_text(text, encoding="utf-8")
        names.append((name, len(text)))
    git("commit", "-q", "--no-verify", "-m", f"relay: {message}", check=False)
    git("update-ref", MARKER, git("rev-parse", "HEAD").strip())
    STATE.write_text(json.dumps(st))
    folder = json.loads(CONFIG.read_text())["drive_folder_id"]
    print(f"Packed {len(names)} bundle(s). Upload each, in this order, with the Google Drive create_file tool:")
    for name, size in names:
        print(f"  title={name}.txt  parentId={folder}  contentMimeType=text/plain  "
              f"disableConversionToGoogleType=true  textContent=<exact contents of .relay/out/{name}.txt> "
              f"({size} chars)")
    print("Print a bundle with: cat .relay/out/<name>.txt   (copy it exactly; every file is hash-checked)")
    return 0


def pending(names_file: str) -> int:
    uploaded = sorted({re.sub(r"\.txt$", "", n.strip()) for n in Path(names_file).read_text().split()
                       if NAME_RE.match(n.strip())})
    applied = _load_applied()
    waiting = [n for n in uploaded if n not in applied]
    print(json.dumps({"uploaded": len(uploaded), "applied": len([n for n in uploaded if n in applied]),
                      "waiting": waiting}, indent=1))
    return 1 if waiting else 0


# -------------------------------------------------------------------- action side
def _load_applied() -> dict:
    return json.loads(APPLIED.read_text()) if APPLIED.exists() else {}


def parse(text: str) -> dict:
    lines = text.replace("\r\n", "\n").split("\n")
    if not lines or lines[0].strip() != "PQC-CHANGE 1":
        raise ValueError("not a PQC change bundle")
    meta, runs, i = {}, [], 1
    while i < len(lines) and not lines[i].startswith("=== "):
        if ":" in lines[i]:
            k, v = lines[i].split(":", 1)
            if k.strip() == "run":
                runs.append(v.strip())
            else:
                meta[k.strip()] = v.strip()
        i += 1
    ops = []
    ended = False
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^=== (FILE|B64) (\S+) sha256=([0-9a-f]{64})(?: lines=(\d+))?$", line)
        if m:
            kind, path, digest, _ = m.groups()
            j = i + 1
            while j < len(lines) and not lines[j].startswith("=== "):
                j += 1
            body = "\n".join(lines[i + 1:j]) + "\n"
            data = body.encode("utf-8") if kind == "FILE" else base64.decodebytes(body.encode())
            if sha(data) != digest:
                raise ValueError(f"{path}: content does not match its sha256 (copied inexactly?)")
            ops.append(("write", path, data))
            i = j
            continue
        m = re.match(r"^=== DELETE (\S+)$", line)
        if m:
            ops.append(("delete", m.group(1), None))
        elif line == "=== END":
            ended = True
            break
        i += 1
    if not ended:
        raise ValueError("bundle is truncated (no === END)")
    for _, path, _ in ops:
        if not allowed(path) or ".." in path.split("/"):
            raise ValueError(f"{path}: not a path a session may change")
    return {"meta": meta, "runs": runs, "ops": ops}


def _run(cmd: list[str], timeout: int = 3600) -> tuple[int, str]:
    p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=timeout)
    return p.returncode, (p.stdout + p.stderr)[-3000:]


def apply_bundle(name: str, text: str) -> dict:
    """Apply one bundle on top of the working tree; returns the applied.json entry."""
    try:
        b = parse(text)
    except ValueError as exc:
        return {"status": "rejected", "reason": str(exc)}
    maps = set()   # the tree is clean here (each bundle is committed), so a failure rolls back to HEAD
    for op, path, data in b["ops"]:
        target = ROOT / path
        if op == "write":
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            if re.match(r"^scripts/maps/[a-z0-9_]+\.py$", path):
                maps.add(path)
        elif target.exists():
            target.unlink()
    log = []
    try:
        for script in sorted(maps):
            mid = Path(script).stem
            code, out = _run([sys.executable, script])
            if code:
                raise RuntimeError(f"map generator {script} failed:\n{out}")
            _run([sys.executable, "scripts/map_preview.py", mid, f"production/previews/{mid}.png", "--points"])
            log.append(f"map {mid} regenerated")
        for r in b["runs"]:
            m = re.match(r"^episode_commit (\d+)$", r)
            if not m:
                raise RuntimeError(f"unknown run step {r!r}")
            n = int(m.group(1))
            site = json.loads((ROOT / "wiki" / "data" / "site.json").read_text())
            code, out = _run([sys.executable, "scripts/run_episode.py", str(n), "--agent", "--commit",
                              "--wiki-url", site["site_url"]])
            if code:
                raise RuntimeError(f"episode {n} did not complete:\n{out}")
            _run([sys.executable, "scripts/contact_sheet.py", str(n)])
            log.append(f"episode {n} committed")
        code, out = _run([sys.executable, "-m", "unittest", "discover", "-s", "tests", "-q"], timeout=1800)
        if code:
            raise RuntimeError(f"tests failed:\n{out}")
    except (RuntimeError, subprocess.TimeoutExpired) as exc:
        git("reset", "-q", "--hard")
        git("clean", "-qfd", check=False)   # untracked files only; ignored ones (vendor/) stay
        return {"status": "rejected", "reason": str(exc)[-2000:], "message": b["meta"].get("message", "")}
    return {"status": "applied", "message": b["meta"].get("message", ""), "session": b["meta"].get("session"),
            "did": log}


def _commit(name: str, entry: dict) -> None:
    applied = _load_applied()
    applied[name] = {**entry, "at": now()}
    APPLIED.write_text(json.dumps(applied, indent=1, ensure_ascii=False) + "\n")
    git("add", "-A")   # vendor/ and .relay/ are ignored
    verb = "Apply" if entry["status"] == "applied" else "Reject"
    git("commit", "-q", "-m", f"{verb} {name}: {entry.get('message', '')}"[:200], check=False)


def apply_all(items: list[tuple[str, callable]]) -> int:
    applied = _load_applied()
    todo = [(n, load) for n, load in sorted(items) if n not in applied]
    print(f"{len(items)} bundle(s) in the folder, {len(todo)} new")
    episodes = 0
    for name, load in todo:
        entry = apply_bundle(name, load())
        print(f"{name}: {entry['status']}" + (f" - {entry.get('reason', '')[:300]}" if entry["status"] != "applied" else ""))
        _commit(name, entry)
        episodes += sum(1 for d in entry.get("did", []) if d.startswith("episode"))
    out = os.environ.get("GITHUB_OUTPUT")
    if out:
        with open(out, "a") as fh:
            fh.write(f"changed={'true' if todo else 'false'}\nepisodes={episodes}\n")
    return 0


def drive_items() -> list[tuple[str, callable]]:
    key = os.environ.get("DRIVE_API_KEY", "").strip()
    folder = json.loads(CONFIG.read_text())["drive_folder_id"]
    if not key:
        raise SystemExit("Missing the DRIVE_API_KEY secret.")

    def get(url, params):
        full = url + "?" + urllib.parse.urlencode(params)
        try:
            with urllib.request.urlopen(full, timeout=60) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            raise SystemExit(f"Drive request failed ({e.code}): {e.read().decode('utf-8', 'replace')[:300]}\n"
                             "Check the folder is shared as 'Anyone with the link' and the key has the Drive API.")

    files, token = [], None
    while True:
        params = {"q": f"'{folder}' in parents and trashed = false", "key": key,
                  "fields": "nextPageToken, files(id, name, mimeType)", "pageSize": 1000}
        if token:
            params["pageToken"] = token
        page = json.loads(get(API, params))
        files += page.get("files", [])
        token = page.get("nextPageToken")
        if not token:
            break
    items = []
    for f in files:
        if not NAME_RE.match(f["name"]):
            continue
        name = re.sub(r"\.txt$", "", f["name"])
        if f["mimeType"].startswith("application/vnd.google-apps"):
            load = (lambda f=f: get(f"{API}/{f['id']}/export", {"mimeType": "text/plain", "key": key})
                    .decode("utf-8-sig"))
        else:
            load = lambda f=f: get(f"{API}/{f['id']}", {"alt": "media", "key": key}).decode("utf-8-sig")  # noqa: E731
        items.append((name, load))
    return items


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 1
    cmd = argv[0]
    if cmd == "begin":
        return begin(argv[1])
    if cmd == "pack":
        ep = [int(argv[i + 1]) for i, a in enumerate(argv) if a == "--episode-commit"]
        msg = next((a for a in argv[1:] if not a.startswith("--") and not a.isdigit()), "update")
        return pack(msg, ep)
    if cmd == "pending":
        return pending(argv[1])
    if cmd == "check-drive":   # cheap: how many bundles are waiting (no downloads)
        if not os.environ.get("DRIVE_API_KEY", "").strip():
            print("::warning::The DRIVE_API_KEY secret is not set; nothing to apply until it is.")
            new = []
        else:
            new = [n for n, _ in drive_items() if n not in _load_applied()]
        print(f"new={len(new)}")
        if os.environ.get("GITHUB_OUTPUT"):
            with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
                fh.write(f"new={len(new)}\n")
        return 0
    if cmd == "apply-drive":
        return apply_all(drive_items())
    if cmd == "apply-dir":
        d = Path(argv[1])
        return apply_all([(p.stem, lambda p=p: p.read_text(encoding="utf-8")) for p in d.glob("change-*.txt")])
    print(__doc__)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
